services:
  mysql:
    image: mysql:latest
    container_name: magalums-mysql
    restart: always
    environment:
      MYSQL_DATABASE: magaludb
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_USER: magalu
      MYSQL_PASSWORD: senha123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
